# https://gohugo.io/overview/configuration/

baseurl: "https://til.sagargiri.com/"
disablePathToLower: false
languageCode: en-us
title: TIL
theme: hugo-octopress

# Number of blog posts displayed on each pagination page.
# No need for pagination in the current setup.
# paginate: 0

# Frontmatter will be in yaml.
metadataformat: yaml

# Only generate HTML output for these places. No need for RSS/XML/whatever.
outputs:
  section:
    - HTML
  taxonomy:
    - HTML

# Permalink URL type. Don't change this because it will invalidate all old links
# unless you like to do a ton of aliases. Add `url:` to your new posts instead.
permalinks:
  post: "/blog/:year-:month-:day-:title/"

# Menu
menu:
  # Navigation menu.
  # All links except home ("/") will open in a new window.
  # Template: {{theme-dir}}/layouts/partials/navigation.html.
  main:
    - Name: About Me!
      URL: /about/
      weight: 2
    - Name: Source Repo
      URL: "https://github.com/girisagar46/til"
      weight: 5


  # Sidebar menu items.
  sidebar:
    - Name: Python
      URL: /categories/python/
      weight: 2
    - Name: Django
      URL: /categories/django/
      weight: 5

# Parameters.
params:

  # Open all menu links in a new window.
  navigationNewWindow: true

  # Sidebar configuration.
  # Disable recent posts section in the sidebar.
  sidebarRecentLimit: 0
  # The big, bold text on top of the sidebar.
  sidebarHeader: Who am I?
  # Appears directly under the sidebar header.
  sidebarText: |-
    I am Sagar, a software engineer specialized in Django backend.
    
    Click on [About Me!](/about/) to know more.

  # Enable links in the side bar. They are under menu.sidebar.
  sidebarMenuEnabled: true
  # Name of the links section.
  sidebarMenuHeader: Collections

  # Sidebar links
  keybase: "https://keybase.io/girisagar46/"
  github: "https://github.com/girisagar46/"
  linkedin: "https://www.linkedin.com/in/girisagar46"


  # 404 page. Header and text.
  notfoundHeader: There's nothing here.
  notfoundText: You can never go back.

  # Do not display all posts' content on the front page (and in pagination).
  truncate: true

  # Author's name. Appears in metadata and under posts.
  author: Sagar

  # Text that appears in the website header under the website title.
#  subtitle: |-
#    The knowledge of anything, since all things have causes, is not acquired or
#    complete unless it is known by its causes. - Avicenna

  # Search engine URL.
  searchEngineURL: "https://www.google.com/search"

  # "Continue Reading" text that appears under truncated posts.
  continueReadingText: Continue Reading...

  # # Enable the RSS icon in navigation.
  rss: true

  description: ""
  defaultKeywords:
    - Sagar Giri
    - Sagar
    - python
    - django

  # Enable table of contents for post by setting this to true. Otherwise, you
  # can enable/disable them individually via frontmatter.
  # tableOfContents: false

  # Generate taxonomy list under /categories/ and /tags/
  generateTaxonomyList: true

  # Use the compact index.
  compactIndex: true

# markup for Hugo v.60+
markup:
  # Note to future me: The reason is because new links in Goldmark are not
  # opened in a new tab by default. We can use the render hook to make it happen
  # for just markdown links but not image links or linkify links (i.e., URLs in
  # the markdown documents as-is). So before you come and waste a lot of time to
  # switch to Goldmark, don't. Of course, unless this problem has been solved in
  # Goldmark.
  # defaultMarkdownHandler: blackfriday # use Blackfriday
  # blackFriday:
  #   fractions: false
  #   hrefTargetBlank: true
  #   latexDashes: false
  #   nofollowLinks: true
  #   smartDashes: false
  #   smartypants: false

  # Goodbye blackfriday, you have been deprecated.
  # The render hook is not fired for linkify links in Goldmark so we have to
  # replace all of them.
  goldmark:
    extensions:
      typographer: false
    renderer:
      hardWraps: false
      unsafe: true

  # Change the defaults for the toc because I want to render every heading in
  # the document.
  tableOfContents:
    endLevel: 7
    startLevel: 1
    # Note to future me: Consider changing the start level to 2 but then you
    # have to go and change it for every blog post that started with a level 1
    # heading.
  highlight:
    # use solarized-dark to highlight code.
    lineNoStart: 1
    lineNos: true
    noHl: false
    style: "base16-snazzy"
    tabWidth: 4
